weather_check/image_handle/urls.py
# -*- coding: utf-8 -*-
# FileName  : urls.py

from django.urls import path
from . import views

app_name = 'image_handle'
urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.check, name='check'),
    path('upload_img/', views.upload_img, name='upload_img'),
    path('check_img/', views.check_img, name='check_img'),
]


weather_check/weather_check/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_handle.urls', namespace='image_handle')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


weather_check/image_handle/models.py
from django.db import models


class ImageCheck(models.Model):
    file_name = models.CharField(max_length=200, verbose_name='图片名')
    file_url = models.CharField(max_length=250, verbose_name='图片URL')
    check_result = models.CharField(max_length=100, verbose_name='识别结果', blank=True)
    check_time = models.DateTimeField(auto_now_add=True, verbose_name='检测时间')

    class Meta:
        db_table = 'image_check'
        verbose_name = '图片检测'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.file_name

weather_check/image_handle/views.py
import os
import numpy as np
from PIL import Image
from django.conf import settings
from django.shortcuts import render
from .models import ImageCheck
from utils import restful
from utils.image_check import check_handle


def index(request):
    return render(request, 'index.html')


def check(request):
    return render(request, 'check.html')


def upload_img(request):
    # 图片上传
    file = request.FILES.get('file')
    file_name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, file_name), 'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    upload_url = request.build_absolute_uri(settings.MEDIA_URL + file_name)
    try:
        ImageCheck.objects.create(file_name=file_name, file_url=upload_url)
    except ImageCheck:
        return restful.server_error(message='数据库发生错误！')
    return restful.ok(data={'url': upload_url})


def check_img(request):
    # 图片检测
    image_url = request.POST.get('img_url')
    if not image_url:
        return restful.params_error(message='缺少必要的参数image_url')
    image_name = image_url.rsplit('/')[-1]
    image_path = os.path.join(settings.MEDIA_ROOT, image_name)
    pred_name = check_handle(image_path)

    try:
        obj = ImageCheck.objects.filter(file_name=image_name).last()
        obj.check_result = pred_name
        obj.save()
    except:
        return restful.server_error(message='数据库发生错误')
    return restful.ok(data={'flower': pred_name, 'chance': str(pred_name) or '0'})

weather_check/front/templates/check.html
{% extends 'front_base.html' %}

{% block title %}
    使用
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="{% static 'css/AdminLTE.css' %}">
    <link rel="stylesheet" href="{% static 'css/upload.min.css' %}">

    <script src="{% static 'js/check.js' %}"></script>


{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>上传一张图片进行识别</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form action="" class="form-group">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="thumbnail-form">上传图片</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="img-url" name="img_url">
                                <span class="input-group-btn">
                                        <label class="btn btn-default btn-file">
                                            <input hidden type="file" id="upload-btn" value="上传图片">上传图片
                                        </label>
                                    </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="progress" style="display: none">
                                <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar"
                                     aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 0">
                                    0
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary pull-right" id="img-change">检测</button>
                        <div class="input-image">
                            <span>上传的图片</span>
                            {#                            <img src="http://cdn.shiqianlong.top/test.jpg" alt=""#}
                            {#                                 class="input-image-file">#}
                            <img src="http://cdn.shiqianlong.top/test.jpg" alt=""
                                 class="input-image-file">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

weather_check/front/templates/front_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--视口设置，适配移动端-->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>识别系统{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/xfzajax.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/zlalert.js' %}"></script>

    {% block header %}

    {% endblock %}

</head>
<body>
<!--去掉导航条的圆角-->
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">

        <!--定义菜单-->
        <div class="collapse navbar-collapse" id="mymenu">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'image_handle:index' %}">简介</a>
                </li>

                <li>
                    <a href="{% url 'image_handle:check' %}">检测</a>
                </li>
                <li>
                    <a href="http://127.0.0.1:8000/admin/" target="_blank">后台管理</a>
                </li>
            </ul>

        </div>
    </div>
</div>


<div class="main">
    <div class="container">
        {% block main-container %}

        {% endblock %}
    </div>
</div>

<div class="footer ">
    <div class="container">
        <div class="row footer-top">
            <div class="col-sm-6 col-lg-6">
                <h4></h4>
                <p>欢迎你加入，这里有你想要的.</p>
            </div>
            <div class="col-sm-6  col-lg-5 col-lg-offset-1">
                <div class="row about">
                    <div class="col-xs-3">
                        <h4>关于</h4>
                        <ul class="list-unstyled">
                            <li>
                                <a href="">关于我们</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-3">
                        <h4>联系方式</h4>
                        <ul class="list-unstyled">

                            <li>
                                <a href="">电子邮件</a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <hr>
        <div class="row footer-bottom">
        </div>
    </div>
</div>
</body>
</html>

weather_check/front/templates/index.html
{% extends 'front_base.html' %}

{% block title %}
    首页
{% endblock %}


{% block header %}
    <link rel="stylesheet" href="{% static 'css/index.min.css' %}">
{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>天气图像识别系统
                <small>人工智能项目</small>
            </h1>
        </div>
        <div class="box-body">
            <div class="box-info">
                <div class="info-image">
                    <div class="box-image">
                        <img src="{% static 'image/rain1.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/sunrise1.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/index3.jpg' %}" alt="">
                    </div>
                </div>
                <div class="box-content">
                    <p>1. 这是一个天气图像识别项目，基于tensorflow，使用卷积神经网络实现对多云，雨天，晴天，日出等天气场景进行识别
                        </p>
                    <p>2. 通过对1070张数据集图片进行训练生成训练模型，模型预测精度90%，使用django框架将数据结果进行显示，并增加后台管理系统方便使用信息的查看</p>

                </div>
            </div>
        </div>
    </div>
{% endblock %}